#!/bin/env python
#
#restart of fff services (elasticsearch and hltd)
#
import os,sys
sys.path.append('/opt/hltd/python')
sys.path.append('/opt/hltd/lib')
from hltd import hltd
from subprocess import Popen
from subprocess import PIPE
from applianceumount import stopFUs
from applianceumount import checkMode
import time
import syslog


def executeService(service,commands):
   arr = [os.path.join('/etc/init.d',service)]
   arr.append(commands)
   proc = Popen(arr, stdout=PIPE)
   output = proc.communicate()[0]
   time.sleep(.1)
   if proc.returncode==0:
       print commands+' '+service+ ':\t\t\t\t [  \033[1;32mOK\033[0;39m  ]'
       return 0
   else:
      print commands + ' ' + service + ' return code:'+str(proc.returncode)+' :\t\t\t\t [  \033[1;31mFAILED\033[0;39m  ]'
      print 'command output:\n',output
      return proc.returncode

def reconfigureScript(services=['elasticsearch','hltd']):
  if 'hltd' in services:
      proc = Popen(['/etc/init.d/hltd','status'], stdout=PIPE)
      output = proc.communicate()[0]
      if 'is running' in output:
        print "Unable to reconfigure if hltd already running"
        return 1

  if 'elasticsearch' in services:
    proc = Popen(['/etc/init.d/elasticsearch','status'], stdout=PIPE)
    output = proc.communicate()[0]
    if proc.returncode==0:
      print "Unable to reconfigure if elasticsearch already running"
      return 1

  #TODO:detect problems in execution of the reconfigure script
  if services == ['elasticsearch','hltd']:
    proc = Popen('/opt/fff/configurefff.sh', stdout=PIPE, stderr=PIPE)
  else:
    proc = Popen(['/opt/fff/configurefff.sh',services[0]], stdout=PIPE, stderr=PIPE)
  output = proc.communicate()[0]
  if proc.returncode!=0:
      print 'Failed to run reconfigure script: ',output
      return 1
  time.sleep(.1)
  return 0

if __name__ == "__main__":

  if len(sys.argv) ==2:

    if 'start' == sys.argv[1]:
        if reconfigureScript()==0:
            rc1=executeService('elasticsearch','start')
            rc2=executeService('hltd','start')
            sys.exit(rc1|rc2)
        else:
            sys.exit(1)

    elif 'stop' == sys.argv[1]:
        rc1=executeService('hltd','stop')
        rc2=executeService('elasticsearch','stop')
        sys.exit(rc1|rc2)

    elif 'restart' == sys.argv[1]:

        executeService('hltd','stop')
        executeService('elasticsearch','stop')
        time.sleep(.5)
        if reconfigureScript()==0:
            rc1=executeService('elasticsearch','restart')
            rc2=executeService('hltd','restart')
            sys.exit(rc1|rc2)
        else:
            sys.exit(1)

    elif 'status' == sys.argv[1]:
      rc1=executeService('hltd',sys.argv[1])
      rc2=executeService('elasticsearch',sys.argv[1])
      sys.exit(rc1|rc2)

    else:
        print "Unknown command"
        sys.exit(1)

  elif len(sys.argv) > 2:

        if sys.argv[1]!='hltd' and sys.argv[1]!='elasticsearch':
            print "Unrecognized service",sys.argv[1]
            sys.exit(1)

        if 'start' == sys.argv[2]:

            if reconfigureScript([sys.argv[1]])==0:
                rc1 = executeService(sys.argv[1],'start')
                sys.exit(rc1)
            else:
                sys.exit(1)

        elif 'stop' == sys.argv[2]:
            rc1 = executeService(sys.argv[1],'stop')
            sys.exit(rc1)

        elif 'restart' == sys.argv[2]:
            executeService(sys.argv[1],'stop')

            if reconfigureScript([sys.argv[1]])==0:
                rc1=executeService(sys.argv[1],'restart')
                sys.exit(rc1)
            else:
                sys.exit(1)

        elif 'status' == sys.argv[2]:
            rc1=executeService(sys.argv[1],'status')
            sys.exit(rc1)

        else:
            print "Unknown command"
            sys.exit(1)

  else:
    print "usage: %s |hltd|elasticsearch start|stop|restart|status" % sys.argv[0]
    sys.exit(1)

sys.exit(0)
